name: surya
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11

  - poetry=1.8.4

  - pytorch==2.5.1
  - pytorch-cuda==12.4

  - streamlit==1.41.1

  - pip:
    - -e ./surya
    - gradio==5.8.0
    # for label-studio development and test
    - -r label/requirements_base.txt
    - -r label/requirements_dev.txt
    - -r label/requirements_test.txt
    # fix compatibility issue keep same with poetry lock file
    - transformers==4.48.1
