name: surya
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11

  - poetry=1.8.4

  - conda-forge::pytorch==2.12.0
  - conda-forge::pytorch-gpu==2.12.0

  - pip:
    - -e ./surya
    # for streamlit
    - streamlit==1.57.0
    # for gradio
    - gradio==5.8.0
    # for label-studio conda and test group
    - -r label/requirements.conda.txt
    - -r label/requirements.test.txt
    # for run_ocr_errors feat
    - pdftext==0.6.3
