name: surya
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10

  - poetry=1.8.4

  - pytorch==2.4.1
  - pytorch-cuda==12.4

  - streamlit==1.40.2

  - pip:
    - -e ./surya
    - gradio==5.8.0
