name: surya
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11

  - poetry=1.8.4

  - conda-forge::pytorch==2.7.0
  - conda-forge::pytorch-gpu==2.7.0

  - pip:
    - -e ./surya
    # for streamlit
    - streamlit==1.57.0
    # for gradio
    - gradio==5.8.0
    # for label-studio development and test
    - -r label/requirements_base.txt
    - -r label/requirements_dev.txt
    - -r label/requirements_test.txt
