

services:
  surya_app:
    image: xiaoyao9184/surya:0.21.0
    container_name: surya_ocr_app
    environment:
      - TORCH_DEVICE=cpu
      - SURYA_INFERENCE_BACKEND=llamacpp
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - DOCKER_HF_CACHE_PATH=/root/.cache/huggingface
    ports:
      - "8501:8501"
    volumes:
      - ./../../cache:/root/.cache
