ARG SURYA_VERSION=0.16.0
ARG STREAMLIT_VERSION=1.40.2
ARG GRADIO_VERSION=5.8.0

FROM pytorch/pytorch:2.7.0-cuda12.6-cudnn9-runtime

ARG SURYA_VERSION
ARG STREAMLIT_VERSION
ARG GRADIO_VERSION

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    surya-ocr==${SURYA_VERSION} \
    pdftext==0.5.0 \
    streamlit==${STREAMLIT_VERSION} \
    streamlit-drawable-canvas-jsretry \
    gradio==${GRADIO_VERSION} \
    pydantic==2.10.5 \
    gunicorn==22.0.0 \
    git+https://github.com/HumanSignal/label-studio-ml-backend.git@1a37d2f#egg=label-studio-ml \
    boto3==1.35.91

COPY ./gradio /workspace/gradio
COPY ./label /workspace/label

EXPOSE 8501
EXPOSE 7860
EXPOSE 9090

VOLUME /root/.cache
VOLUME /workspace/label/.pytest_cache
# VOLUME /workspace/label/cache.db

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV LABEL_STUDIO_URL=http://label-studio:8080

CMD ["surya_gui"]
