

services:
  surya_gradio:
    image: xiaoyao9184/surya:0.12.1
    container_name: surya_ocr_gradio
    working_dir: /workspace/gradio
    command: gradio gradio_app.py
    environment:
      - TORCH_DEVICE=cuda
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_02_18
      - LAYOUT_MODEL_CHECKPOINT=/root/.cache/datalab/models/layout/2025_02_18
      - RECOGNITION_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_recognition/2025_02_18
      - TABLE_REC_MODEL_CHECKPOINT=/root/.cache/datalab/models/table_recognition/2025_02_18
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - TEXIFY_MODEL_CHECKPOINT=/root/.cache/datalab/models/texify/2025_02_18
      - INLINE_MATH_MODEL_CHECKPOINT=/root/.cache/datalab/models/inline_math_detection/2025_02_18
    ports:
      - "7860:7860"
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
