

services:
  surya_gradio:
    image: xiaoyao9184/surya:0.20.0
    container_name: surya_ocr_gradio
    working_dir: /workspace/gradio
    command: gradio gradio_app.py
    environment:
      - TORCH_DEVICE=cuda
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - DOCKER_HF_CACHE_PATH=/root/.cache/huggingface
      # NOT work Still downloading the main version from HF, so switch use model path
      # - VLLM_EXTRA_ARGS=--revision ac7f775 --tokenizer-revision ac7f775 --code-revision ac7f775
      - SURYA_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--datalab-to--surya-ocr-2/snapshots/ac7f77523d5e293e3ce67bf0ae02450378ee9aad        
      - SURYA_GGUF_LOCAL_MODEL_PATH=/root/.cache/huggingface/hub/models--datalab-to--surya-ocr-2-gguf/snapshots/6a3a4c30e5e74446d4f8b6afd05b2f2da970f470/surya-2.gguf
      - SURYA_GGUF_LOCAL_MMPROJ_PATH=/root/.cache/huggingface/hub/models--datalab-to--surya-ocr-2-gguf/snapshots/6a3a4c30e5e74446d4f8b6afd05b2f2da970f470/surya-2-mmproj.gguf
    ports:
      - "7860:7860"
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
