

services:
  surya_gradio:
    image: xiaoyao9184/surya:master
    container_name: surya_ocr_gradio
    working_dir: /workspace/gradio
    command: gradio gradio_app.py
    environment:
      - TORCH_DEVICE=cpu
    ports:
      - "7860:7860"
    volumes:
      - ./../../cache:/root/.cache
