

services:
  labelstudio:
    image: heartexlabs/label-studio
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=label@localhost
      - LABEL_STUDIO_PASSWORD=label.123
      - LABEL_STUDIO_USER_TOKEN=label-token
    ports:
      - "8080:8080"
    container_name: label-studio

  surya_label:
    image: xiaoyao9184/surya:0.20.0
    container_name: surya-ocr-label
    working_dir: /workspace/label
    command: label-studio-ml start --root-dir /workspace label
    environment:
      - LABEL_STUDIO_API_KEY=label-token
      - TORCH_DEVICE=cuda
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - DOCKER_HF_CACHE_PATH=/root/.cache/huggingface
      # NOT work Still downloading the main version from HF, so switch use model path
      # - VLLM_EXTRA_ARGS=--revision ac7f775 --tokenizer-revision ac7f775 --code-revision ac7f775
      - SURYA_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--datalab-to--surya-ocr-2/snapshots/ac7f77523d5e293e3ce67bf0ae02450378ee9aad        
      - SURYA_GGUF_LOCAL_MODEL_PATH=/root/.cache/huggingface/hub/models--datalab-to--surya-ocr-2-gguf/snapshots/6a3a4c30e5e74446d4f8b6afd05b2f2da970f470/surya-2.gguf
      - SURYA_GGUF_LOCAL_MMPROJ_PATH=/root/.cache/huggingface/hub/models--datalab-to--surya-ocr-2-gguf/snapshots/6a3a4c30e5e74446d4f8b6afd05b2f2da970f470/surya-2-mmproj.gguf
    ports:
      - "9090:9090"
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
