FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./surya /app
RUN pip3 install --no-cache-dir \
    -e . \
    transformers==4.48.1 \
    pdftext==0.5.0 \
    streamlit==1.41.1 \
    gradio==5.8.0 \
    pydantic==2.10.5 \
    gunicorn==22.0.0 \
    git+https://github.com/HumanSignal/label-studio-ml-backend.git@master#egg=label-studio-ml \
    boto3==1.35.91
# The image is too large, exceeding 30GB.
# RUN pip3 install poetry
# RUN poetry install --no-root --with dev

COPY ./gradio /workspace/gradio
COPY ./label /workspace/label

EXPOSE 8501
EXPOSE 7860
EXPOSE 9090

VOLUME /root/.cache
VOLUME /workspace/label/.pytest_cache
# VOLUME /workspace/label/cache.db

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV LABEL_STUDIO_URL=http://label-studio:8080

CMD ["surya_gui"]
