FROM pytorch/pytorch:2.12.0-cuda12.6-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./surya /app
# The image is too large, with layers exceeding 10GB.
# RUN pip3 install poetry
# RUN poetry install --no-root --with dev
RUN pip3 install --no-cache-dir \
    -e .

# Lock streamlit version
RUN pip3 install --no-cache-dir \
    streamlit==1.57.0 \
    pdftext==0.6.3

# Lock gradio version
RUN pip3 install --no-cache-dir \
    gradio==5.8.0

# Lock label-studio version
RUN pip3 install --no-cache-dir \
    Flask==3.1.3 \
    colorama==0.4.6 \
    requests==2.34.2 \
    semver==3.0.4 \
    label-studio-sdk==1.0.10 \
    gunicorn==22.0.0 \
    boto3==1.35.91

# No-deps label-studio version
RUN pip3 install --no-cache-dir --no-deps \
    git+https://github.com/HumanSignal/label-studio-ml-backend.git@b06ebeb#egg=label-studio-ml

# Override incorrect version
RUN pip3 install --no-cache-dir \
    pydantic==2.10.5

COPY ./gradio /workspace/gradio
COPY ./label /workspace/label

EXPOSE 8501
EXPOSE 7860
EXPOSE 9090

VOLUME /root/.cache
VOLUME /workspace/label/.pytest_cache
# VOLUME /workspace/label/cache.db

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV LABEL_STUDIO_URL=http://label-studio:8080

CMD ["surya_gui"]
