ARG SURYA_VERSION=0.16.1
ARG STREAMLIT_VERSION=1.40.2
ARG GRADIO_VERSION=5.8.0


FROM alpine/curl:latest AS fonts

WORKDIR /fonts

RUN curl -L -o /fonts/GoNotoCurrent-Regular.ttf https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoCurrent-Regular.ttf \
    && curl -L -o /fonts/GoNotoCJKCore.ttf https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoCJKCore.ttf


FROM pytorch/pytorch:2.7.0-cuda12.6-cudnn9-runtime

ARG SURYA_VERSION
ARG STREAMLIT_VERSION
ARG GRADIO_VERSION

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir \
    surya-ocr==${SURYA_VERSION} \
    pdftext==0.5.0 \
    streamlit==${STREAMLIT_VERSION} \
    streamlit-drawable-canvas-jsretry \
    gradio==${GRADIO_VERSION} \
    pydantic==2.10.5

# fix The Poetry configuration is invalid miss name of project
# https://github.com/HumanSignal/label-studio-sdk/pull/380
RUN git config --global url."https://github.com/xiaoyao9184/label-studio-sdk".insteadOf "https://github.com/HumanSignal/label-studio-sdk" \
    && pip3 install --no-cache-dir \
    gunicorn==22.0.0 \
    boto3==1.35.91 \
    git+https://github.com/HumanSignal/label-studio-ml-backend.git@1a37d2f#egg=label-studio-ml \
    && git config --global --unset url."https://github.com/xiaoyao9184/label-studio-sdk".insteadOf

# COPY --from=fonts /fonts/GoNotoCurrent-Regular.ttf /fonts/GoNotoCurrent-Regular.ttf
# COPY --from=fonts /fonts/GoNotoCJKCore.ttf /fonts/GoNotoCJKCore.ttf
COPY --from=fonts /fonts/GoNotoCurrent-Regular.ttf /opt/conda/lib/python3.11/site-packages/static/fonts/GoNotoCurrent-Regular.ttf
COPY --from=fonts /fonts/GoNotoCJKCore.ttf /opt/conda/lib/python3.11/site-packages/static/fonts/GoNotoCJKCore.ttf

COPY ./gradio /workspace/gradio
COPY ./label /workspace/label

EXPOSE 8501
EXPOSE 7860
EXPOSE 9090

VOLUME /root/.cache
VOLUME /workspace/label/.pytest_cache
# VOLUME /workspace/label/cache.db

ENV APP_PATH=/app
ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV LABEL_STUDIO_URL=http://label-studio:8080

CMD ["surya_gui"]
