

services:
  surya_gradio:
    image: xiaoyao9184/surya:0.20.0
    container_name: surya_ocr_gradio
    working_dir: /workspace/gradio
    command: gradio gradio_app.py
    environment:
      - SURYA_INFERENCE_BACKEND=llamacpp
      - TORCH_DEVICE=cpu
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - DOCKER_HF_CACHE_PATH=/root/.cache/huggingface
    ports:
      - "7860:7860"
    volumes:
      - ./../../cache:/root/.cache
