

services:
  surya_llm:
    image: vllm/vllm-openai:v0.20.1
    container_name: surya_ocr_llm
    command:
      - "--model"
      - "datalab-to/surya-ocr-2"
      - "--no-enforce-eager"
      - "--max-num-seqs"
      - "24"
      - "--dtype"
      - "bfloat16"
      - "--max-model-len"
      - "18000"
      - "--max-num-batched-tokens"
      - "8192"
      - "--gpu-memory-utilization"
      - "0.85"
      - "--enable-prefix-caching"
      - "--mm-processor-kwargs"
      - '{"min_pixels": 3136, "max_pixels": 6291456}'
      - "--served-model-name"
      - "datalab-to/surya-ocr-2"
      - "--speculative-config"
      - '{"method": "mtp", "num_speculative_tokens": 2}'
    ports:
      - 8000
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  surya_app:
    image: xiaoyao9184/surya:0.20.0
    container_name: surya_ocr_app
    environment:
      - SURYA_INFERENCE_URL=http://surya_ocr_llm:8000/v1
      - TORCH_DEVICE=cuda
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - DOCKER_HF_CACHE_PATH=/root/.cache/huggingface
    ports:
      - "8501:8501"
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
